name: POC on Ant based Java project
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up IBM ACE environment
      run: |
        powershell -Command ". 'C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile'"

    - name: Run Build.xml using ANT command
      run: |
        ant -noinput -buildfile C:\krpoc\BillPayment\build.xml
