name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:
    # Use GitHub's default hosted runner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Set up SSH connection using password (sshpass)
    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Test SSH Connection to Remote Server
      env:
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      run: |
        # Test SSH connection
        echo "Attempting to SSH into $REMOTE_USER@$REMOTE_HOST"
        sshpass -p $REMOTE_PASSWORD ssh -v -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "echo 'SSH connection successful'"

    - name: Connect to remote server and run build
      env:
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      run: |
        # Connect via SSH and execute commands remotely
        sshpass -p $REMOTE_PASSWORD ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
          echo "Connected to remote server"

          # Run the mqsiprofile command and build the project using Ant
          source /opt/ibm/mqsi/ace-12.0.3.0/server/bin/mqsiprofile
          echo "mqsiprofile has been executed."
          echo "Running build.xml"
          ant -noinput -buildfile BillPayment/build.xml
        EOF
