name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Verify IBM MQ environment
      shell: pwsh
      run: |
        # Display the PATH to ensure mqsilist is in it
        echo $Env:PATH

    - name: Run Build.xml using ANT command
      shell: pwsh
      run: |
        # Source the mqsiprofile script to set the environment
        & "C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile"

        # Now you can run additional ACE commands, for example, mqsilist
        mqsilist
