name: Connect to RHEL VM without SSH Key
on:
  push:
    branches:
      - main

jobs:
  connect-to-rhel-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Ping the RHEL VM
        run: ping -c 4 192.168.18.74

