Reading package lists...
Building dependency tree...
Reading state information...
sshpass is already the newest version (1.09-1).
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
0s
Run echo "Home directory is: $HOME"
Home directory is: /home/runner
drwxr-x--- 14 runner docker 4096 Dec 24 15:15 /home/runner
drwxr-xr-x 2 runner docker 4096 Dec 24 15:16 /home/runner/.ssh
5s
Run ssh-keyscan -H 192.168.18.74 >> $HOME/.ssh/known_hosts
  
Error: Process completed with exit code 1.
