name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Add IBM MQ tools to PATH manually and run mqsilist
      shell: pwsh
      run: |
        # Add IBM MQ tools to PATH manually, ensuring to handle the space in "Program Files"
        $Env:PATH += ";C:\Program Files\IBM\ACE\12.0.7.0\server\bin"
        
        # Source the mqsiprofile script to set the environment in the current session (with quotes)
        & "C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile"

        # Run mqsilist to verify the environment and list the integration nodes
        mqsilist
