name: POC on Ant based Java project
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Run Build.xml using ANT command
      run: |
        #Run build.xml using ant command
        "ant -noinput -buildfile C:\Program Files\BillPayment\build.xml"

