name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run Build.xml using ANT command
      shell: bash
      run: |
        # Source the mqsiprofile
        . "C:/PROGRA~1/IBM/ACE/12.0.7.0/server/bin/mqsiprofile"
        ant -noinput -buildfile C:/krpoc/BillPayment/build.xml
