# This workflow will build a Java project with Ant

name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run mqsiprofile
      run: |
        source /opt/ibm/mqsi/ace-12.0.3.0/server/bin/mqsiprofile
        # Replace with the actual path to your mqsiprofile script
        echo "mqsiprofile has been executed."

    - name: Build with Ant
      run: ant -noinput -buildfile BillPayment/build.xml
