name: POC on Ant based Java project
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run Ant Build via Wrapper Script
      shell: cmd
      run: |
        echo "Starting wrapper script..."
        C:\krpoc\build_wrapper.bat
