# This workflow will build a Java project with Ant
name: POC on Ant based Java project 
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run Build.xml using ANT command
      shell: pwsh
      run: |
        \C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile

