name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Add IBM MQ tools to PATH and run mqsilist
      shell: pwsh
      run: |
        # Add IBM MQ tools to PATH manually, ensuring spaces in path are handled
        $Env:PATH += ";C:\Program Files\IBM\ACE\12.0.7.0\server\bin"
        
        # Use cmd.exe to source mqsiprofile, as this sets environment variables properly
        cmd.exe /C ""C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile" && mqsilist"

    - name: Verify environment variables
      shell: pwsh
      run: |
        # Check the updated PATH
        echo $Env:PATH

        # Verify if mqsilist is available
        Get-Command mqsilist
