name: POC on Ant based Java project
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Source mqsiprofile and Run Ant Build
      shell: cmd
      run: |
        echo "Sourcing mqsiprofile..."
        call C:\PROGRA~1\IBM\ACE\12.0.7.0\server\bin\mqsiprofile.bat
        echo "Environment variables:"
        set MQSI_VERSION
        echo "Running Ant build..."
        ant -noinput -buildfile C:\krpoc\BillPayment\build.xml
