name: POC on Ant based Java project
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
 
    steps:
    - uses: actions/checkout@v4

    - name: Source mqsiprofile and run Ant build
      run: |
        echo "Sourcing mqsiprofile"
        . "C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile"
        echo "Environment variables:"
        echo $MQSI_VERSION
        echo "Running Ant build..."
        ant -noinput -buildfile C:\krpoc\BillPayment\build.xml
