name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Add IBM MQ tools to PATH manually
      run: |
        $Env:PATH += ";C:\Program Files\IBM\ACE\12.0.7.0\server\bin"
        mqsiprofile


