# This workflow will build a Java project with Ant
name: POC on Ant based Java project 
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run Build.xml using ANT command
      run: |
        source C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile
        echo "mqsiprofile has been executed"
        echo "Run build.xml"
        ant -noinput -buildfile BillPayment/build.xml

    - name: Run the mqsideploy command to deploy the bar file
      run: |
        echo "deploy bar file"
        mqsideploy Ace12Node -e Default -a C:\BillPayment\release\SigService-25.2.1.0001.bar
