name: POC on Ant based Java project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run Build.xml using ANT command
      shell: cmd
      run: |
        :: Source the mqsiprofile
        call C:\Program Files\IBM\ACE\12.0.7.0\server\bin\mqsiprofile.cmd
        :: Verify environment variable
        set MQSI_VERSION
        :: Running Ant build
        ant -noinput -buildfile C:\krpoc\BillPayment\build.xml
